// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineLearningPlatformAss2.Data.Entities;

#nullable disable

namespace OnlineLearningPlatformAss2.Data.Migrations
{
    [DbContext(typeof(OnlineLearningSystemDbContext))]
    [Migration("20260207080853_AddLastViewedLessonIdToEnrollment4")]
    partial class AddLastViewedLessonIdToEnrollment4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.AssessmentOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("option_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("option_text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<string>("SkillLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("skill_level");

                    b.HasKey("OptionId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_Assessment_Options_question_id");

                    b.ToTable("Assessment_Options", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("question_type");

                    b.HasKey("QuestionId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Assessment_Questions_category_id");

                    b.ToTable("Assessment_Questions", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Blog", b =>
                {
                    b.Property<Guid>("BlogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("blog_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("BlogId");

                    b.HasIndex(new[] { "AuthorId" }, "IX_Blogs_author_id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.HasKey("CategoryId");

                    b.HasIndex(new[] { "ParentId" }, "IX_Categories_parent_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Certificate", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("issue_date");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pdf_url");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("serial_number");

                    b.HasKey("CertificateId");

                    b.HasIndex(new[] { "EnrollmentId" }, "IX_Certificates_enrollment_id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool>("IsFromAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_from_admin");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("MessageId")
                        .HasName("PK__Chat_Mes__0BBF6EE6D1CE85A6");

                    b.HasIndex(new[] { "ReceiverId" }, "IX_Chat_Messages_receiver_id");

                    b.HasIndex(new[] { "SenderId" }, "IX_Chat_Messages_sender_id");

                    b.ToTable("Chat_Messages", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("instructor_id");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("is_featured");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("English")
                        .HasColumnName("language");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("All Levels")
                        .HasColumnName("level");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("CourseId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Courses_category_id");

                    b.HasIndex(new[] { "InstructorId" }, "IX_Courses_instructor_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.CourseReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("review_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("PK__Course_R__60883D90AA711BB2");

                    b.HasIndex(new[] { "CourseId" }, "IX_Course_Reviews_course_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Course_Reviews_user_id");

                    b.ToTable("Course_Reviews", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid?>("LastViewedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Enrollments_course_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Enrollments_user_id");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LearningPath", b =>
                {
                    b.Property<Guid>("PathId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("path_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCustomPath")
                        .HasColumnType("bit")
                        .HasColumnName("is_custom_path");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("SourceAssessmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("source_assessment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("PathId");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_Learning_Paths_created_by_user_id");

                    b.ToTable("Learning_Paths", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("module_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video_url");

                    b.HasKey("LessonId");

                    b.HasIndex(new[] { "ModuleId" }, "IX_Lessons_module_id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LessonComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("comment_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("PK__Lesson_C__E79576870300F7CD");

                    b.HasIndex(new[] { "LessonId" }, "IX_Lesson_Comments_lesson_id");

                    b.HasIndex(new[] { "ParentId" }, "IX_Lesson_Comments_parent_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Lesson_Comments_user_id");

                    b.ToTable("Lesson_Comments", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LessonProgress", b =>
                {
                    b.Property<Guid>("ProgressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("progress_id");

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_summary");

                    b.Property<int>("AiSummaryStatus")
                        .HasColumnType("int")
                        .HasColumnName("ai_summary_status");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_accessed_at");

                    b.Property<int?>("LastWatchedPosition")
                        .HasColumnType("int")
                        .HasColumnName("last_watched_position");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Transcript")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transcript");

                    b.HasKey("ProgressId");

                    b.HasIndex(new[] { "EnrollmentId" }, "IX_Lesson_Progress_enrollment_id");

                    b.HasIndex(new[] { "LessonId" }, "IX_Lesson_Progress_lesson_id");

                    b.ToTable("Lesson_Progress", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("module_id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("ModuleId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Modules_course_id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("notification_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842FECA777A8");

                    b.HasIndex(new[] { "UserId" }, "IX_Notifications_user_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Option", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("option_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("OptionId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_Options_question_id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("PathId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("path_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Orders_course_id");

                    b.HasIndex(new[] { "PathId" }, "IX_Orders_path_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Orders_user_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.PathCourse", b =>
                {
                    b.Property<Guid>("PathId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("path_id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("PathId", "CourseId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Path_Courses_course_id");

                    b.ToTable("Path_Courses", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_profiles_UserId")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("QuestionId");

                    b.HasIndex(new[] { "QuizId" }, "IX_Questions_quiz_id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Quiz", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quiz_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<double>("PassingScore")
                        .HasColumnType("float")
                        .HasColumnName("passing_score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("QuizId");

                    b.HasIndex(new[] { "LessonId" }, "IX_Quizzes_lesson_id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("attempt_id");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("attempted_at");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit")
                        .HasColumnName("passed");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quiz_id");

                    b.Property<double>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("AttemptId");

                    b.HasIndex(new[] { "QuizId" }, "IX_Quiz_Attempts_quiz_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Quiz_Attempts_user_id");

                    b.ToTable("Quiz_Attempts", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TransactionGateId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_gate_id");

                    b.HasKey("TransactionId");

                    b.HasIndex(new[] { "OrderId" }, "IX_Transactions_order_id");

                    b.HasIndex(new[] { "TransactionGateId" }, "IX_Transactions_transaction_gate_id")
                        .IsUnique()
                        .HasFilter("([transaction_gate_id] IS NOT NULL)");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssessmentCompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assessment_completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasCompletedAssessment")
                        .HasColumnType("bit")
                        .HasColumnName("has_completed_assessment");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "IX_users_RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.UserAnswer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("answer_id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assessment_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("selected_option_id");

                    b.HasKey("AnswerId");

                    b.HasIndex(new[] { "AssessmentId" }, "IX_User_Answers_assessment_id");

                    b.HasIndex(new[] { "QuestionId" }, "IX_User_Answers_question_id");

                    b.HasIndex(new[] { "SelectedOptionId" }, "IX_User_Answers_selected_option_id");

                    b.ToTable("User_Answers", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.UserAssessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result_summary");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("AssessmentId");

                    b.HasIndex(new[] { "UserId" }, "IX_User_Assessments_user_id");

                    b.ToTable("User_Assessments", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.UserLearningPathEnrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid>("PathId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("path_id");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int")
                        .HasColumnName("progress_percentage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex(new[] { "PathId" }, "IX_User_Learning_Path_Enrollments_path_id");

                    b.HasIndex(new[] { "UserId" }, "IX_User_Learning_Path_Enrollments_user_id");

                    b.ToTable("User_Learning_Path_Enrollments", (string)null);
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wishlist_id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("WishlistId")
                        .HasName("PK__Wishlist__6151514ECFDDC1A5");

                    b.HasIndex(new[] { "CourseId" }, "IX_Wishlists_course_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Wishlists_user_id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.AssessmentOption", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.AssessmentQuestion", "Question")
                        .WithMany("AssessmentOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Category", "Category")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Blog", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Category", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Certificate", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Enrollment", "Enrollment")
                        .WithMany("Certificates")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "Receiver")
                        .WithMany("ChatMessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_ChatMessages_Receiver");

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "Sender")
                        .WithMany("ChatMessageSenders")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Sender");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Course", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.CourseReview", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Course", "Course")
                        .WithMany("CourseReviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseReviews_Courses");

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("CourseReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseReviews_Users");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Enrollment", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LearningPath", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "CreatedByUser")
                        .WithMany("LearningPaths")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Lesson", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LessonComment", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Lesson", "Lesson")
                        .WithMany("LessonComments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LessonComments_Lessons");

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.LessonComment", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_LessonComments_Parent");

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("LessonComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LessonComments_Users");

                    b.Navigation("Lesson");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LessonProgress", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Enrollment", "Enrollment")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Lesson", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("LessonId")
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Module", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Notification", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Option", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Order", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Course", "Course")
                        .WithMany("Orders")
                        .HasForeignKey("CourseId");

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.LearningPath", "Path")
                        .WithMany("Orders")
                        .HasForeignKey("PathId");

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Path");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.PathCourse", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Course", "Course")
                        .WithMany("PathCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.LearningPath", "Path")
                        .WithMany("PathCourses")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Path");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Profile", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("OnlineLearningPlatformAss2.Data.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Question", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Quiz", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.QuizAttempt", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Transaction", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.User", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.UserAnswer", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.UserAssessment", "Assessment")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.AssessmentQuestion", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.AssessmentOption", "SelectedOption")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.UserAssessment", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("UserAssessments")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.UserLearningPathEnrollment", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.LearningPath", "Path")
                        .WithMany("UserLearningPathEnrollments")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("UserLearningPathEnrollments")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Path");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Wishlist", b =>
                {
                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.Course", "Course")
                        .WithMany("Wishlists")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Courses");

                    b.HasOne("OnlineLearningPlatformAss2.Data.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Users");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.AssessmentOption", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.AssessmentQuestion", b =>
                {
                    b.Navigation("AssessmentOptions");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Category", b =>
                {
                    b.Navigation("AssessmentQuestions");

                    b.Navigation("Courses");

                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Course", b =>
                {
                    b.Navigation("CourseReviews");

                    b.Navigation("Enrollments");

                    b.Navigation("Modules");

                    b.Navigation("Orders");

                    b.Navigation("PathCourses");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Enrollment", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("LessonProgresses");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LearningPath", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PathCourses");

                    b.Navigation("UserLearningPathEnrollments");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Lesson", b =>
                {
                    b.Navigation("LessonComments");

                    b.Navigation("LessonProgresses");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.LessonComment", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Order", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizAttempts");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("ChatMessageReceivers");

                    b.Navigation("ChatMessageSenders");

                    b.Navigation("CourseReviews");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("LearningPaths");

                    b.Navigation("LessonComments");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Profile");

                    b.Navigation("QuizAttempts");

                    b.Navigation("UserAssessments");

                    b.Navigation("UserLearningPathEnrollments");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("OnlineLearningPlatformAss2.Data.Entities.UserAssessment", b =>
                {
                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
